### PR TITLE
Indev

### PR DESCRIPTION
**Pull request by Flowx**
First working build.
Currently only reports last thrown error but Im working on a full in-depth stacktrace.

### CODE REVIEW

**Comment by butchcom** [comment]
nice

**Comment by CapsAdmin** [comment]
I don't know your goal with this is, but have you thought about just doing all of this in luajit with ffi?

**Comment by Flowx** [comment]
@CapsAdmin I need a universal portable host which i can deploy on multiple platforms. This project is in a very early stage right now. Usage of the FFI library would require me to already have a running LuaJIT host.

**Comment by CapsAdmin** [comment]
@Flowx I'm not sure what you mean here. When you compile LuaJIT for/on a platform it supports it will work on that platform. Are you saying you want to support something other than LuaJIT?'

I mean you can compile LuaJIT on windows to luajit.exe and then run "luajit.exe main.lua" and do all the directory watching and whatnot in FFI from there. Same goes with Linux and macOS. 

It has pros and cons of course. You could argue writing functionality in C++ is cleaner and that's fine.

It's just an idea I was curious if you had thought about. I'm always interested in LuaJIT projects.

**Comment by Flowx** [comment]
@CapsAdmin My goal is to have a somewhat managed plaform. I know that youre very familiar with Garrys Mod LuaJIT implementation, this project will have some similarities with it. Im planning on writing my own additional libraries that implement events (hooks) and stuff like serial interfaces, HTTP, TCP over IP. Pretty much "unlocking" Lua. Of course i could do all this in FFI but on a bigger scale it would be impossible to manage.

**Pull request merged**
